# Generated by Django 5.2.7 on 2025-11-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('escritor', models.CharField(max_length=200)),
                ('editora', models.CharField(max_length=200)),
                ('progresso', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('EP', 'Em progresso'), ('L', 'Lido')], default='EP', max_length=2)),
            ],
        ),
    ]
